test:
    make
sudo: false
python:
  - "2.7"
language: python
before_install:
    - pip install coveralls
install:
    - make install
    - pip install codecov
    - python setup.py install
script: nosetests --with-coverage --cover-package=namebot
after_success:
    - coveralls
    - codecov
