test:
    make
sudo: false
python:
  - "2.7"
language: python
install:
    - make install
    - pip install coveralls
    - python setup.py install
script: nosetests --with-coverage --cover-package=namebot
after_success:
    coveralls
